import streamlit as st
st.title("Welcome! this is the portfolio of :blue[Indraneel Roy] :sunglasses:")
st.header("Presently working as a Data Science intern at Innomatics!")
st.subheader(":orange[How to connect]")
st.text("LinkedIn|Github|Gmail")
st.subheader(":orange[Educational background]")
st.text("BTech CSE(AIML) - Dronacharya college of Engineering, Gurgaon (2020-24)")
st.text("Class XII - Delhi Public School, Faridabad")
st.text("Class X - Apeejay School, Faridabad")
st.subheader(":orange[Tech Stack]")
st.text("-Python Programming")
st.text("-Numpy")
st.text("-Pandas")
st.text("-Matplotlib")
st.text("-Seaborn")
st.text("-Sklearn")
st.subheader(":orange[Soft Skills]")
st.text("-Excellent communication skills")
st.text("-Teamwork")
st.text("-Time management")
st.subheader(":orange[Projects]")
st.text("-Web scraping on New York Times article using Beautiful Soup and requests")
st.text("-Exploratory Data Analysis of content categories on SocialBuzz platform")
st.text("-Myopia prediction model using supervised machine learning (ongoing)")
st.subheader(":orange[Certifications]")
st.text("-Machine Learning Specialization by Deeplearning.ai and Coursera")
st.text("-Python Programming for Artificial Intelligence by Udemy")
st.text("-Data Analytics Virtual Experience by Accenture and Forage")
st.text("-Data Analysis with Python by Cognitiveclass.ai IBM Skills Network")
